export const BREAKPOINT_SCREEN_XS = 480;
export const BREAKPOINT_SCREEN_SM = 768;
export const BREAKPOINT_SCREEN_MD = 992;
export const BREAKPOINT_SCREEN_LG = 1200;
export const BREAKPOINT_SCREEN_XS_MAX = BREAKPOINT_SCREEN_SM - 1;
export const BREAKPOINT_SCREEN_SM_MIN = BREAKPOINT_SCREEN_SM;
export const BREAKPOINT_SCREEN_SM_MAX = BREAKPOINT_SCREEN_MD - 1;
export const BREAKPOINT_SCREEN_MD_MIN = BREAKPOINT_SCREEN_MD;
export const BREAKPOINT_SCREEN_MD_MAX = BREAKPOINT_SCREEN_LG - 1;
export const BREAKPOINT_SCREEN_LG_MIN = BREAKPOINT_SCREEN_LG;

const breakpoints = {
  xs: BREAKPOINT_SCREEN_XS,
  sm: BREAKPOINT_SCREEN_SM,
  md: BREAKPOINT_SCREEN_MD,
  lg: BREAKPOINT_SCREEN_LG,
};

export default breakpoints;
